even_week= true
day_id= 2
date= "27 October 2025"
group= "P3112"
[[schedule]]
title= "Основы дискретной математики"
format= "Очный"
class_number= 2337
teacher_name= "Поляков Владимир Иванович"
[schedule.type]
title= "Лекция"
[schedule.building]
address= "Кронверкский пр., д.49, лит.А"
[schedule.time]
start_time= "09:50"
finish_time= "11:20"
[[schedule]]
title= "Основы дискретной математики"
format= "Очно - дистанционный"
class_number= 2337
teacher_name= "Поляков Владимир Иванович"
[schedule.type]
title= "Практика"
[schedule.building]
address= "Кронверкский пр., д.49, лит.А"
[schedule.time]
start_time= "11:30"
finish_time= "13:00"
[[schedule]]
title= "ОПД"
format= "Очный"
class_number= 1333
teacher_name= "Деменев Тимур Гурбанович"
[schedule.type]
title= "Лабораторная"
[schedule.building]
address= "Кронверкский пр., д.49, лит.А"
[schedule.time]
start_time= "13:30"
finish_time= "15:00"
[[schedule]]
title= "ОПД"
format= "Очный"
class_number= 1333
teacher_name= "Деменев Тимур Гурбанович"
[schedule.type]
title= "Лабораторная"
[schedule.building]
address= "Кронверкский пр., д.49, лит.А"
[schedule.time]
start_time= "15:30"
finish_time= "17:00"
